### ISSUE TITLE
error:   File "LinkedInt.py", line 388, in <module>

### ISSUE THREAD

**Issue by superuser5** [vysecurity/LinkedInt#11]
error while running it:

[*] Enter search Keywords (use quotes for more precise results)
googler

[*] Enter filename for output (exclude file extension)
search.txt

[*] Filter by Company? (Y/N): 
y

[*] Specify a Company ID (Provide ID or leave blank to automate): 

[*] Enter e-mail domain suffix (eg. contoso.com): 
google.com           

[*] Select a prefix for e-mail generation (auto,full,firstlast,firstmlast,flast,firstl,first.last,fmlast,lastfirst): 
auto

[*] Automatically using Hunter IO to determine best Prefix
[!] Rate limited by Hunter IO trial
Traceback (most recent call last):
  File "LinkedInt.py", line 388, in <module>
    prefix = content['data']['pattern']
KeyError: 'data'

**Comment by robisonr** [comment]
I have the same exact error.

**Comment by KyanHexagon** [comment]
I get the error above in both Ubuntu and Kali Linux.

**Comment by vysecurity** [comment]
Fixed. Feel free to sponsor open source research at https://github.com/sponsors/vysecurity
