### ISSUE TITLE
need of help

### ISSUE THREAD

**Issue by MariaRusanova** [vysecurity/LinkedInt#14]
Hello Group,

I'm receiving the following errors after executing of requirements.txt

Collecting pkg-resources==0.0.0 (from -r requirements.txt (line 5))
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 5)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 5))

Could you please check why?

Also when I'm trying to execute LinkedInt.py receiving:

┌─[✗]─[root@parrot]─[~/LinkedInt]
└──╼ #python LinkedInt.py 
Traceback (most recent call last):
  File "LinkedInt.py", line 27, in <module>
    from thready import threaded
ImportError: No module named thready

Can you guide me what I have to do to pass this?

nano requirements.txt

beautifulsoup4==4.6.0
certifi==2018.1.18
chardet==3.0.4
idna==2.6
pkg-resources==0.0.0
requests==2.18.4
thready==0.1.5
urllib3==1.22

**Comment by EnigmaMe** [comment]
You just have to install thready with `pip install thready` then you can run it.

**Comment by DarknightCanada** [comment]
did it work for you? even after pip install thready I am getting

`root@kali:~/LinkedInt# python LinkedInt.py
Traceback (most recent call last):
  File "LinkedInt.py", line 27, in <module>
    from thready import threaded
ImportError: No module named thready
root@kali:~/LinkedInt# python3 LinkedInt.py
  File "LinkedInt.py", line 61
    cookie = requests.utils.dict_from_cookiejar(s.cookies)
                                                         ^
TabError: inconsistent use of tabs and spaces in indentation
root@kali:~/LinkedInt# python LinkedInt.py
Traceback (most recent call last):
  File "LinkedInt.py", line 27, in <module>
    from thready import threaded
ImportError: No module named thready
`

**Comment by MariaRusanova** [comment]
I can give a feedback that unfortunately the command `pip install thready` didn't help. :/

I executed as recommended EnigmaMe and after that I executed again the command for the script python LinkedInt.py

output: 

```
root@kali:~/LinkedInt# python LinkedInt.py
Traceback (most recent call last):
  File "LinkedInt.py", line 15, in <module>
    import requests
ImportError: No module named requests
```

~ this time I tried with kali, not parrot. Informative for the version of the kali:
```
root@kali:~/LinkedInt# uname -srm
Linux 5.7.0-kali1-amd64 x86_64
```

**Comment by vysecurity** [comment]
Works on latest Ubuntu or Debian based distros like Linux. Just pip install -r requirements.txt and use python3.

Fixed. Feel free to sponsor open source research at https://github.com/sponsors/vysecurity
