### ISSUE TITLE
Login functionality issues?

### ISSUE THREAD

**Issue by tajyoder** [vysecurity/LinkedInt#18]
Hello,

Attempted to use this tool today after a hiatus, and I'm receiving an error "Cannot log in." I've verified that my credentials are properly entered in LinkedInt.cfg, but the issue remains. Not sure what's going on or if others are experiencing similar. Perhaps LinkedIn recently updated their login process?

**Comment by MatthieuLaRosaSimon** [comment]
Everything good for me. i have issues but not this one. Maybe too many sessions are open on your LinkedIn account, try closing them directly using your account in a web browser

**Comment by vysecurity** [comment]
I'll take a look at this one shortly.

**Comment by vysecurity** [comment]
Temporary fix is to stick the cookie in manually.

**Comment by vysecurity** [comment]
Fixed. Feel free to sponsor open source research at https://github.com/sponsors/vysecurity
