### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by anonymousxx90** [vysecurity/LinkedInt#19]
Hi bro, can u write detail installation instructions? Thanks

**Comment by vysecurity** [comment]
@kgretzky what do you think?

**Comment by rasta-mouse** [comment]
🤯🔫

**Comment by vysecurity** [comment]
Sir @anonymousxx90, apologies. Our operation is currently experiencing heavy delay due to increased demand for support. Please bare with us while you stay on the line.

**Comment by vysecurity** [comment]
Will consider at a later date. The instructions are already very verbose.
