### ISSUE TITLE
Could not find a version that satisfies the requirement pkg-resources==0.0.0

### ISSUE THREAD

**Issue by wifiuk** [vysecurity/LinkedInt#2]
I get the following error when pip install -r requirements.txt

Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 5)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 5))

**Comment by muirror** [comment]
I just removed that line from the requirements folder and reran pip. LinkedInt works just fine once the installation is complete.

**Comment by b4cktr4ck2** [comment]
Had the same issue, the above fix worked for me too.

There's an open PR to remove this line: https://github.com/vysecurity/LinkedInt/pull/8

**Comment by vysecurity** [comment]
Fixed. Feel free to sponsor open source research at https://github.com/sponsors/vysecurity
