### ISSUE TITLE
LinkedInt Unable To Run

### ISSUE THREAD

**Issue by zealias** [vysecurity/LinkedInt#3]
Executing LinkedInt breaks mouse cursor. The below command was ran with regular user.

./LinkedInt.py 
import-im6.q16: not authorized `sys' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `re' @ error/constitute.c/WriteImage/1037.
import-im6.q16: not authorized `time' @ error/constitute.c/WriteImage/1037.
^C
^C
^C

^C
^C
^C

c
^C
^C
^C

^C
^Cfrom: can't read /var/mail/bs4
from: can't read /var/mail/thready
./LinkedInt.py: line 30: syntax error near unexpected token `sys'
./LinkedInt.py: line 30: `reload(sys)'

**Comment by talilama** [comment]
Try running it as "python LinkedInt.py" instead of just ./LinkedInt.py.

**Comment by vysecurity** [comment]
Fixed. Feel free to sponsor open source research at https://github.com/sponsors/vysecurity
